spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketflow
    username: ticketflow
    password: ticketflow
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    locations: classpath:db/migration